site_name: Moonlander Optimal Control
site_description: Optimal control formulation and analysis inspired by the classic Lunar Lander.
theme:
  name: material
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Methodology: methodology.md
  - Results: results.md
  - Notebooks: notebooks.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
plugins:
  - search

